Add some input-checking
and use the jq expression I've currently got on my laptop

diff --git a/bin/json_schema b/bin/json_schema
--- a/bin/json_schema
+++ b/bin/json_schema
@@ -1,37 +1,45 @@
 #!/usr/bin/env bash
 
+# Copyright 2014-2019 Noah Sussman New Media, LLC
+
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+
+#     http://www.apache.org/licenses/LICENSE-2.0
+
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+
 if [ -z "$1" ]
 then
     echo "Usage: `basename $0` <path to JSON file>"
-  exit 1
+    exit 1
+elif [ ! -f "$1" ]
+then
+    echo "Usage: $(basename $0) <JSON file>"
+    echo "ERROR: Not a file: $1"
+    exit 1
+elif [ ! -x "$(which jq)" ]
+then
+    echo "ERROR: jq is not in your path!"
+    exit 1
 fi
 
-is_required () {
-    command_name="$1"
-    help_text="Install it via your package manager (eg: brew, yum, apt-get)."
-
-    command -v ${command_name} >/dev/null 2>&1 \
-        || (echo >&2 "ERROR: ${command_name} is required!"
-            echo >&2 "    ${help_text}"
-            echo >&2 "ERROR: Please install ${command_name} and try again!"
-            exit 1)
-}
-
-is_required "jq"
-is_required "sort"
-is_required "uniq"
-
 jq --raw-output \
-   'paths
-    | map(
-        . as $item
-        | type
-        | if  . == "number" then
-          "[n]"
-          else $item
-          end)
-    | join(".")
-    | .' \
-   $1 \
+        'paths
+        | map(. as $item
+            | type
+            | if . == "number" then
+                  "[]"
+              else
+                  "[\"" + $item + "\"]"
+              end)
+        | join("")
+        | "." + .' \
+    "$1" \
     | sort \
     | uniq -c
